blog/urls.py
from django.urls import path
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from blog.views import *
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [

    path('blog/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('blog/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='blogpost_detail'),
    path('blog/create/', never_cache(BlogPostCreateView.as_view()), name='blogpost_form'),
    path('blog/edit/<int:pk>/', never_cache(BlogPostUpdateView.as_view()), name='blogpost_update'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users')),
    path('', include ('blog.urls', namespace='blog')),
]

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page, never_cache

from mailing.views import *
from .apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    # Home
    path('', home_view, name='home_page'),
    # MailingSettings
    path('mailings', MailingListView.as_view(), name='mailing_list'),
    path('mailings/<int:pk>/', cache_page(60)(MailingDetailView.as_view()), name='mailing_detail'),
    path('mailings/create/', never_cache(MailingCreateView.as_view()), name='mailing_form'),
    path('mailings/update/<int:pk>/', never_cache(MailingUpdateView.as_view()), name='mailing_update'),
    path('mailings/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    # Manager status Ended
    path('end_mailing/<int:pk>/', EndMailingView.as_view(), name='end_mailing'),
    # Client
    path('clients/create/', never_cache(ClientCreateView.as_view()), name='client_form'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/update/<int:pk>/', never_cache(ClientUpdateView.as_view()), name='client_update'),
    path('clients/detail/<int:pk>/', cache_page(60)(ClientDetailView.as_view()), name='client_detail'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # Logs
    path('logs/<int:pk>/', view_mailing_logs, name='mailing_logs'),
    # Message
    path('mailing/message/update/<int:pk>/', never_cache(MailingMessageUpdateView.as_view()), name='mailing_message_update'),
    path('mailing/message/create/<int:pk>/', never_cache(MailingMessageCreateView.as_view()), name='mailing_message_create'),
]

users/urls.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path, reverse_lazy, include
from . import views
from .apps import UsersConfig
from .views import RegisterView, EmailVerificationView, BlockUserView, CustomLoginView
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<uuid:email_verification_code>/', EmailVerificationView.as_view(), name='email_verification'),
    # path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name="users/password_reset_email.html",
                                                      from_email=settings.EMAIL_HOST_USER,
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='update_password'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('block_user/', BlockUserView.as_view(), name='block_user'),

]

mailing/models.py
from django.contrib.auth import get_user_model
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='Электронная почта')
    name = models.CharField(max_length=250, verbose_name='ФИО')
    comment = models.TextField(max_length=250, verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(get_user_model(), related_name='clients', on_delete=models.CASCADE,
                              verbose_name='Пользователь', **NULLABLE)

    def __str__(self):
        return f'{self.name} ({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class MailingSettings(models.Model):
    TIME_CHOICES = [('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')]
    STATUS_CHOICES = [('C', 'Created'), ('R', 'Running'), ('E', 'Ended')]

    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь', **NULLABLE)
    time = models.DateTimeField()
    periodicity = models.CharField(max_length=1, choices=TIME_CHOICES)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    recipients = models.ManyToManyField(Client, through='MailingLog', verbose_name='Получатели')

    def __str__(self):
        return f'{self.time}, {self.periodicity}, {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'


class MailingMessage(models.Model):
    subject = models.CharField(max_length=255, verbose_name='Тема сообщения')
    body = models.TextField(verbose_name='Текст сообщения')
    mailing_settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, related_name='messages')

    def __str__(self):
        return self.subject

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class MailingLog(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='logs')
    mailing_settings = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, related_name='logs')
    attempt_time = models.DateTimeField(auto_now_add=True, verbose_name='дата последней попытки')
    status = models.BooleanField(default=False, verbose_name='статус отправки')
    server_response = models.TextField(verbose_name='ответ почтового сервиса', **NULLABLE)

    def __str__(self):
        return f'{self.status} ({self.attempt_time})'

    class Meta:
        verbose_name = 'Попытка'
        verbose_name_plural = 'Попытки'

mailing/forms.py
from bootstrap_datepicker_plus.widgets import DateTimePickerInput
from django import forms
from .models import MailingSettings, Client, MailingMessage


class MailingForm(forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ['time', 'periodicity', 'status', 'recipients']
        widgets = {
            'time': DateTimePickerInput(format='%Y-%m-%d %H:%M:%S'),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(MailingForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['recipients'].queryset = Client.objects.filter(owner=user)



class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['email', 'name', 'comment']


class MailingMessageForm(forms.ModelForm):
    subject = forms.CharField(label='Тема')
    body = forms.CharField(label='Сообщение', widget=forms.Textarea)

    class Meta:
        model = MailingMessage
        fields = ['subject', 'body']

mailing/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, RedirectView
from mailing.forms import MailingForm, ClientForm, MailingMessageForm
from .models import MailingSettings, Client, MailingMessage, MailingLog
from .services import send_mailing
from blog.models import BlogPost


def home_view(request):
    all_mailings = MailingSettings.objects.all()
    active_mailings = MailingSettings.objects.filter(status='R')
    clients_list = Client.objects.all().distinct()
    blog_posts = BlogPost.objects.all()[:3]

    context = {
        'object_list': all_mailings,
        'active_mailings': active_mailings,
        'clients_list': clients_list,
        'blog_posts': blog_posts,
        'current_page': 'home_page'
    }
    return render(request, 'mailing/home_page.html', context)


class MailingListView(LoginRequiredMixin, ListView):
    model = MailingSettings
    template_name = 'mailing/mailing_list.html'

    def get_queryset(self):
        if self.request.user.is_superuser or self.request.user.groups.filter(name='Managers').exists():
            return MailingSettings.objects.all()
        return MailingSettings.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_mailings'] = MailingSettings.objects.filter(status='R', owner=self.request.user).count()
        return context


class EndMailingView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('mailing:mailing_list')

    def get(self, *args, **kwargs):
        mailing = get_object_or_404(MailingSettings, pk=kwargs['pk'])

        if self.request.user.groups.filter(name='Managers').exists() and mailing.status == 'R':
            mailing.status = 'E'
            mailing.save()

        return super().get(*args, **kwargs)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingForm
    template_name = 'mailing/mailing_form.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.groups.filter(name='Managers').exists():
            return HttpResponseForbidden("У вас нет прав создавать рассылку.")
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message_form'] = MailingMessageForm(self.request.POST or None)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        message_form = context['message_form']

        mailing = form.save(commit=False)
        mailing.owner = self.request.user
        mailing.save()

        if message_form.is_valid():
            message = message_form.save(commit=False)
            message.mailing_settings = mailing
            message.save()

            if mailing.time <= timezone.now():
                send_mailing()

            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = MailingSettings
    template_name = 'mailing/mailing_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_logs = MailingLog.objects.filter(mailing_settings=self.object)
        context['clients'] = [log.client for log in mailing_logs]
        return context


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    template_name = 'mailing/mailing_confirm_delete.html'
    success_url = reverse_lazy('mailing:mailing_list')


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailingForm
    template_name = 'mailing/mailing_update.html'
    success_url = reverse_lazy('mailing:mailing_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        selected_recipients = form.cleaned_data.get('recipients')
        self.object.recipients.set(selected_recipients)

        # Логика на основе статуса
        if self.object.status == 'R':  # Если меняем статус на R (запущена) запускается рассылка.
            print("Рассылка запущена")
            send_mailing()
        elif self.object.status == 'C':  # Создана
            pass
        elif self.object.status == 'E':  # Закончена
            pass

        return super().form_valid(form)


class MailingMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    form_class = MailingMessageForm
    template_name = 'mailing/mailing_message_create.html'
    success_url = reverse_lazy('mailing:mailing_update')

    def form_valid(self, form):
        mailing = get_object_or_404(MailingSettings, pk=self.kwargs['pk'], owner=self.request.user)
        message = form.save(commit=False)
        message.mailing_settings = mailing
        message.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mailing_id'] = self.kwargs.get('pk')
        return context


class MailingMessageUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    template_name = 'mailing/mailing_message_update.html'

    def get_success_url(self):
        return reverse('mailing:mailing_update', args=[self.object.mailing_settings.pk])

    def form_valid(self, form):
        get_object_or_404(MailingSettings, pk=self.object.mailing_settings_id, owner=self.request.user)
        return super().form_valid(form)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'mailing/client_list'

    def get_queryset(self):
        return Client.objects.filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_detail.html'
    success_url = reverse_lazy('mailing:client_list')


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_update.html'

    def get_success_url(self):
        return reverse_lazy('mailing:client_detail', kwargs={'pk': self.object.pk})


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    template_name = 'mailing/client_confirm_delete.html'
    success_url = reverse_lazy('mailing:client_list')


def view_mailing_logs(request, pk):
    logs = MailingLog.objects.filter(mailing_settings_id=pk).order_by('-id')
    return render(request, 'mailing/mailing_logs.html', {'logs': logs})

mailing/templates/mailing/client_confirm_delete.html
{% extends "mailing/base.html" %}

{% block content %}
    <div class="container mt-3">
        <h2>Вы уверены, что хотите удалить этого клиента?</h2>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary">Отмена</a>
        </form>
    </div>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends "mailing/base.html" %}

{% block content %}
<style>
    .detail-item {
        padding: 15px;
        margin-bottom: 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
    }
    .detail-title {
        font-weight: bold;
    }
    .recipient-list li {
        margin: 5px 0;
    }
    .static-textarea {
        white-space: pre-wrap;
    }
    /* Стили для блока actions */
    .actions {
        padding-top: 15px;
    }
    .actions a {
        display: block;
        margin-bottom: 10px;
    }
</style>

<div class="col-md-6 mt-3">
    <div class="row">
        <div class="col-md-8">
            <div class="detail-item">
                <div class="detail-title">Клиент:</div>
                <div style="max-height: 150px; overflow-y: auto;">
                    <ul class="recipient-list">
                        {{ client.name }}
                    </ul>
                </div>
            </div>

            <div class="detail-item">
                <div class="detail-title">Почта:</div>
                <div>{{ client.email }}</div>
            </div>

            <div class="detail-item">
                <div class="detail-title">Комментарий:</div>
                {% if object.comment %}
                <div class="static-textarea">{{ object.comment }}</div>
                {% else %}
                <p>Не заполнено</p>
                {% endif %}
            </div>
        </div>
        <div class="col-md-4 actions">
            <a href="{% url 'mailing:client_update' pk=object.pk %}" class="btn btn-primary mb-2">Редактировать</a>
            <a href="{% url 'mailing:client_delete' pk=object.pk %}" class="btn btn-danger">Удалить</a>
            <p>
                <a href="{% url 'mailing:client_list' %}" class="btn btn-success">Список клиентов</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-3" style="margin-bottom: 100px;">
    <ul class="list-group">
        {% for client in object_list %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-5">
                    <strong>{{ client.name }}</strong>
                    <br>
                    {{ client.email }}
                </div>
                <div class="col-md-5">
                    <p class="text-muted">{{ client.comment }}</p>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'mailing:client_detail' client.id %}" class="btn btn-info btn-sm">Посмотреть</a>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
    <div class="text-center mt-3">
        <p>Добавьте своих клиентов</p>
        <a href="{% url 'mailing:client_form' %}" class="btn btn-success btn-lg w-50">Создать клиента</a>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/home_page.html
{% extends 'mailing/base.html' %}

{% load static %}
{% load mailing_tags %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/my_style.css' %}">

<div class="text-center container py-3">
    <div class="row py-3">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">Mailing service</h1>
            <p class="lead text-body-secondary">Управление вашими рассылками</p>
            <p class="py-1 text-body-secondary">Авторизируйтесь для начала работы</p>
            <p>
                <a href="{% url 'mailing:mailing_list' %}" class="btn btn-success my-1 w-75">Мои рассылки</a>
            </p>
            <p>
                {% if user.is_superuser or not user|has_group:"Managers" %}
                <a href="{% url 'mailing:client_list' %}" class="btn btn-success my-1 w-75">Мои клиенты</a>
                {% endif %}
            </p>
            {% if user.is_superuser or user|has_group:"Managers" %}
            <p>
                <a href="{% url 'users:block_user' %}" class="btn btn-danger my-1 w-75">Список пользователей</a>
            </p>
            {% endif %}
        </div>
    </div>
</div>

<div class="text-center container py-3">
    <div class="row py-2">
        <div class="col-md-4 col-sm-12 mb-2">
            <div class="card card-custom py-3">
                <div class="card-body">
                    <p class="card-text">Количество рассылок: {{ object_list.count }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 mb-2">
            <div class="card card-custom py-3">
                <div class="card-body">
                    <p class="card-text">Количество активных рассылок: {{ active_mailings.count }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12 mb-2">
            <div class="card card-custom py-3">
                <div class="card-body">
                    <p class="card-text">Количество уникальных клиентов: {{ clients_list.count }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="text-center container py-3">
    <h1 class="jumbotron-heading">Создайте свою эффективную рассылку с нами!</h1>
    <p>Просто, быстро и надежно. Начните сегодня и убедитесь в преимуществах нашего сервиса.</p>
    {% if user.is_superuser or not user|has_group:"Managers" %}
    <a href="{% url 'mailing:mailing_form' %}"
       class="btn btn-success my-2 w-25 mt-3 mx-auto d-block d-flex justify-content-center align-items-center">
        Создать рассылку
    </a>
    {% endif %}
</div>

<div class="text-center container py-3">
    <div class="row py-3">
        {% for post in blog_posts %}
        <div class="col-md-4 col-sm-12 mb-2">
            <div class="card card-custom py-3">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <a href="{% url 'blog:blogpost_detail' post.pk %}" class="btn btn-secondary">Читать</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends "mailing/base.html" %}

{% block content %}
<style>
    .detail-item {
        padding: 15px;
        margin-bottom: 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .detail-title {
        font-weight: bold;
    }
    .recipient-list li {
        margin: 5px 0;
    }
    .static-textarea {
        white-space: pre-wrap;
    }
    /* Стили для блока actions */
    .actions {
        text-align: right;
    }
</style>

<div class="container mt-3">
    <div class="row">
        <div class="col-md-8">
            <h4 class="mb-4">Рассылка {{ object.time }}, {{ object.get_periodicity_display }}</h4>
        </div>
         <div class="col-md-4 actions">
            <a href="{% url 'mailing:mailing_logs' object.id %}" class="btn btn-success btn-lg">Посмотреть логи</a>
            <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary btn-lg">Назад</a>
        </div>

    <div class="col-md-6">
        <div class="detail-item">
            <div class="detail-title">Получатели:</div>
            <div style="max-height: 150px; overflow-y: auto;">
                <ul class="recipient-list">
                    {% if clients %}
                    {% for recipient in clients %}
                    <li>{{ recipient.name }} ({{ recipient.email }})</li>
                    {% endfor %}
                    {% else %}
                    <li>Получатели не выбраны</li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="detail-item">
            <div class="detail-title">Периодичность:</div>
            <div>{{ object.get_periodicity_display }}</div>
        </div>

        <div class="detail-item">
            <div class="detail-title">Статус:</div>
            <div>{{ object.get_status_display }}</div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="detail-item">
            <div class="detail-title">Тема:</div>
            {% if object.messages.first.subject %}
            <div class="static-textarea">{{ object.messages.first.subject }}</div>
            {% else %}
            <p>Не заполнено</p>
            {% endif %}
        </div>

        <div class="detail-item">
            <div class="detail-title">Сообщение:</div>
            {% if object.messages.first.body %}
            <div class="static-textarea">{{ object.messages.first.body|linebreaks }}</div>
            {% else %}
            <p>Не заполнено</p>
            {% endif %}
        </div>
    </div>
</div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends "mailing/base.html" %}

{% load static %}
{% load mailing_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/my_style.css' %}">
{% endblock %}

{% block content %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
            {% if not object_list %}
                <p class="text-center">У вас пока нет рассылок. Чтобы создать рассылку, нажмите на кнопку "Создать рассылку"<br> Для рассылки необходимы клиенты, если вы их еще не добавили, сделайте это на главной странице,<br> нажав кнопку "Мои клиенты".
                </p>
            {% else %}
                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for item in object_list %}
                    <div class="col">
                        <div class="card card-custom">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.pk }}</h5>
                                <p class="card-text">Время рассылки: {{ item.time }}</p>
                                <p class="card-text">Периодичность рассылки: {{ item.periodicity }}</p>
                                <p class="card-text">Статус рассылки: {{ item.status }}</p>
                                <div class="d-flex justify-content-between align-items-center mt-4">
                                    <div class="btn-group">
                                        <a href="{% url 'mailing:mailing_detail' item.pk %}"
                                           class="btn btn-sm btn-outline-secondary">View</a>
                                        {% if user.is_superuser or item.owner == user %}
                                        <a href="{% url 'mailing:mailing_update' item.pk %}"
                                           class="btn btn-sm btn-outline-secondary">Edit</a>
                                        <a href="{% url 'mailing:mailing_delete' item.pk %}" class="btn btn-sm btn-danger">Delete</a>
                                        {% endif %}
                                        {% if user|has_group:"Managers" and item.status == 'R' %}
                                        <a href="{% url 'mailing:end_mailing' item.pk %}"
                                           class="btn btn-sm rounded-pill btn-warning">Остановить рассылку</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        <p>
            {% if user.is_superuser or not user|has_group:"Managers" %}
            <a href="{% url 'mailing:mailing_form' %}" class="btn btn-success my-2 w-25 mt-3 mx-auto d-block">Создать рассылку</a>
            {% endif %}
        </p>
    </div>
</main>
{% endblock %}

mailing/templates/mailing/mailing_update.html
{% extends "mailing/base.html" %}
{% load static widget_tweaks %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker3.min.css' %}">
<style>
    .detail-item {
        padding: 15px;
        margin-bottom: 15px;
        border: 1px solid #ddd;
        border-radius: 5px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .detail-title {
        font-weight: bold;
    }
    .recipient-list li {
        margin: 5px 0;
    }
    .recipients-container {
        max-height: 250px;
        overflow-y: auto;
        border: 1px solid #ddd;
        padding: 10px;
        border-radius: 5px;
    }
</style>

<div class="container">
    <h4 class="mb-4">Редактирование настроек рассылки</h4>

    {{ form.errors }}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="row">
            <!-- Левая колонка -->
            <div class="col-md-6">
                <div class="detail-item">
                    <div class="detail-title">Получатели:</div>
                    <div class="recipients-container">
                        <input type="checkbox" id="select_all"/> Выбрать всех<br>
                        {{ form.recipients|add_class:"recipient-checkbox" }}
                        {% if form.recipients.errors %}
                        <div class="errors">
                            {{ form.recipients.errors }}
                        </div>
                        {% endif %}
                    </div>
                </div>

                <div class="form-group">
                    <label for="{{ form.time.id_for_label }}">Время рассылки</label>
                    {{ form.time }}
                </div>

                <div class="detail-item">
                    <div class="detail-title">Периодичность:</div>
                    <div>
                        {{ form.periodicity }}
                    </div>
                </div>
                <div class="detail-item">
                    <div class="detail-title">Статус:</div>
                    <div>
                        {{ form.status }}
                    </div>
                </div>
            </div>
        </div>
        <input type="submit" value="Сохранить изменения" class="btn btn-primary mt-4">
        {% if object.messages.first %}
        <a href="{% url 'mailing:mailing_message_update' object.messages.first.pk %}" class="btn btn-secondary mt-4">Редактировать
            сообщение</a>
        {% else %}
        <a href="{% url 'mailing:mailing_message_create' object.pk %}" class="btn btn-secondary mt-4">Создать
            сообщение</a>
        {% endif %}
    </form>

    <!-- JavaScript для функционала "Выбрать всех" -->
    <script>
        document.getElementById('select_all').addEventListener('click', function() {
            var options = document.querySelectorAll('#id_recipients option');
            for (var option of options) {
                option.selected = this.checked;
            }
        });
    </script>
</div>
{% endblock %}

{% block extra_scripts %}
{{ form.media }}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
{% endblock %}