blog/urls.py
from django.urls import path
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from blog.views import *
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [

    path('blog/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('blog/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='blogpost_detail'),
    path('blog/create/', never_cache(BlogPostCreateView.as_view()), name='blogpost_form'),
    path('blog/edit/<int:pk>/', never_cache(BlogPostUpdateView.as_view()), name='blogpost_update'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users')),
    path('', include ('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from autoslug import AutoSlugField

NULLABLE = {'null': True, 'blank': True}


class BlogPost(models.Model):
    """
    Модель для хранения блогов.
    Содержит заголовок, содержание, изображение и информацию о публикации.
    """
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = AutoSlugField(populate_from='title', unique=True, verbose_name='slug')
    content = models.TextField(verbose_name='содержание')
    image = models.ImageField(upload_to='blog/', verbose_name='изображение', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликован')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ('created_at',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.models import BlogPost


class BlogPostListView(ListView):
    """
    Отображение списка опубликованных блогов, отсортированных по дате создания.
    """
    model = BlogPost
    template_name = 'blog/blogpost_list.html'
    context_object_name = 'blogs'

    def get_queryset(self, *args, **kwargs):
        query = super().get_queryset(*args, **kwargs)
        query = query.filter(is_published=True).order_by('-created_at')

        return query


class BlogPostDetailView(DetailView):
    """
    Отображение детальной информации о блоге и учет количества просмотров.
    """
    model = BlogPost
    template_name = 'blog/blogpost_detail.html'
    context_object_name = 'object'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        self.object.views_count += 1
        self.object.save()

        return self.object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        return context


class BlogPostCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """
    Создание нового блога с указанием основных полей.
    """
    model = BlogPost
    permission_required = 'blog.add_blog'
    fields = ('title', 'content', 'is_published', 'views_count', 'image')
    success_url = reverse_lazy('blog:blogpost_list')

    def form_valid(self, form):
        response = super().form_valid(form)
        if not self.object.image:
            self.object.image = 'media/note_image.jpg'
            self.object.save()
        return response


class BlogPostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """
    Обновление существующего блога.
    """
    model = BlogPost
    permission_required = 'blog.change_blog'
    fields = ('title', 'content', 'is_published', 'views_count', 'image')
    success_url = reverse_lazy('blog:blogs')

    def get_success_url(self):
        return reverse('blog:blogpost_detail', kwargs={'pk': self.object.pk})


class BlogPostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    Удаление блога.
    """
    model = BlogPost
    success_url = reverse_lazy('blog:blogpost_list')

    def test_func(self):
        return self.request.user.is_superuser

blog/templates/blog/blogpost_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-header text-center">
                <h2>Удаление блога</h2>
            </div>
            <div class="card-body">
                <div class="col-12">
                    <h5>Вы уверены, что хотите удалить блог {{ object.title }}?</h5>
                    <div class="6">
                    </div>
                    <div class="6">
                        <form method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Подтвердить удаление</button>
                            <a href="{% url 'blog:blogpost_list' %}" class="btn btn-secondary">Отменить</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_detail.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-between align-items-center mb-3">
                <a href="{% url 'blog:blogpost_list' %}" class="btn btn-secondary"><i class="fa fa-arrow-left"></i> Вернуться к блогам</a>
                <div>
                    {% if perms.blog.change_blog %}
                        <a href="{% url 'blog:blogpost_update' object.pk %}" class="btn btn-outline-primary mr-2">Редактировать</a>
                    {% endif %}
                    {% if user.is_superuser %}
                        <a href="{% url 'blog:blogpost_delete' object.pk %}" class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{ object.title }}</h3>
                    <img src="{{ object.image|mediapath }}" alt="Изображение блога" class="float-right ml-3 mb-3" style="width: 40%; max-width: 300px;">
                    <p class="card-text">{{ object.content }}</p>
                    <div style="clear: both;"></div>
                    <hr>
                    <small class="text-muted">Количество просмотров: {{ object.views_count }}</small>
                    <small class="text-muted">Опубликовано: {{ object.created_at }}</small>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blogpost_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Создать блог</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost_list.html
{% extends 'mailing/base.html' %}
{% load blog_tags %}
{% block content %}
<header class="text-center mt-3"><h2>Мы пишем:</h2></header>
<div class="row">
    {% if perms.blog.add_blog %}
    <div class="col-12 text-center">
        <a href="{% url 'blog:blogpost_form' %}" class="btn btn-lg btn-primary w-25 mt-4">Создать блог</a>
    </div>
    {% endif %}
    {% for object in object_list %}
    <div class="col-4 pt-3">
        <div class="card h-100 d-flex flex-column">
            <div class="card-header text-center m-2">
                <h4>{{ object.title }}</h4>
            </div>
            <div class="card-img text-center" style="height: 200px; overflow: hidden;">
                <img src="{{ object.image|mediapath }}" alt="Изображение блога"
                     style="max-height: 100%; max-width: 100%;">
            </div>
            <div class="card-body flex-grow-1">
                <p class="card-text mt-2">{{ object.content|truncatewords:15 }}</p>
            </div>
            <div class="card-footer">
               <a href="{% url 'blog:blogpost_detail' object.pk %}" class="btn btn-secondary">Читать далее</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-12 text-center">
        <p>Нет статей для отображения.</p>
    </div>
    {% endfor %}
</div>
{% endblock %}