blog/urls.py
from django.urls import path
from django.conf import settings
from django.views.decorators.cache import cache_page, never_cache

from blog.apps import BlogConfig
from blog.views import *
from django.conf.urls.static import static

app_name = BlogConfig.name

urlpatterns = [

    path('blog/', cache_page(60)(BlogPostListView.as_view()), name='blogpost_list'),
    path('blog/<int:pk>/', cache_page(60)(BlogPostDetailView.as_view()), name='blogpost_detail'),
    path('blog/create/', never_cache(BlogPostCreateView.as_view()), name='blogpost_form'),
    path('blog/edit/<int:pk>/', never_cache(BlogPostUpdateView.as_view()), name='blogpost_update'),
    path('blog/delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blogpost_delete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('', include('users.urls', namespace='users')),
    path('', include ('blog.urls', namespace='blog')),
]

users/urls.py
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView
from django.urls import path, reverse_lazy, include
from . import views
from .apps import UsersConfig
from .views import RegisterView, EmailVerificationView, BlockUserView, CustomLoginView
from django.contrib.auth import views as auth_views

app_name = UsersConfig.name

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<uuid:email_verification_code>/', EmailVerificationView.as_view(), name='email_verification'),
    # path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name="users/password_reset_email.html",
                                                      from_email=settings.EMAIL_HOST_USER,
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='update_password'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                     success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('block_user/', BlockUserView.as_view(), name='block_user'),

]

users/models.py
import uuid
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    is_active = models.BooleanField(default=True)

    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    email_verified = models.BooleanField(default=False)
    email_verification_code = models.UUIDField(default=uuid.uuid4, editable=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django import forms
from users.models import User


class UserRegisterForm(UserCreationForm):
    """Форма для регистрации пользователя"""

    class Meta:
        model = User
        fields = ('first_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password1'].help_text = None


class BlockUserForm(forms.Form):
    user_id = forms.IntegerField(widget=forms.HiddenInput())

users/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth import get_user_model, authenticate, login
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.views import View
from django.views.generic.edit import CreateView
from .models import User
from .forms import UserRegisterForm, BlockUserForm
from . import services


class ManagerMixin:
    """
    Mixin для определения, является ли пользователь менеджером и ограничения доступа.
    """

    def is_manager(self):
        return self.request.user.is_authenticated and self.request.user.groups.filter(name='Managers').exists()

    def dispatch(self, request, *args, **kwargs):
        if not self.is_manager():
            return HttpResponseForbidden("У вас нет прав доступа к этой странице.")
        return super().dispatch(request, *args, **kwargs)


class CustomLoginView(LoginView):
    template_name = 'users/login.html'

    def form_valid(self, form):
        if not form.get_user().email_verified:
            messages.error(self.request, 'Пожалуйста, подтвердите свою электронную почту перед входом.')
            return self.render_to_response(self.get_context_data(form=form))
        return super().form_valid(form)

    def form_invalid(self, form):
        User = get_user_model()
        try:
            user = User.objects.get(email=self.request.POST['username'])
            if not user.is_active:
                messages.error(self.request, 'Вам приостановлен доступ к сервису, обратитесь в техническую поддержку.')
        except User.DoesNotExist:
            messages.error(self.request, 'Такой пользователь не обнаружен. Вам необходимо зарегистрироваться.')

        return super().form_invalid(form)


class RegisterView(CreateView):
    """
    Представление для регистрации новых пользователей и
    отправки ссылки для подтверждения по электронной почте.
    """
    model = User
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)

            url = reverse('users:email_verification', args=[self.object.email_verification_code])
            absolute_url = self.request.build_absolute_uri(url)

            services.send_verification(email=self.object.email, url=absolute_url)

            messages.success(self.request, 'Ссылка для верификации отправлена на вашу электронную почту!')
            self.object.save()

        return super().form_valid(form)


class EmailVerificationView(View):
    """
    Обработка подтверждения электронной почты пользователя.
    """

    def get(self, request, email_verification_code):
        try:
            user = User.objects.get(email_verification_code=email_verification_code)
            user.email_verified = True
            user.save()
            messages.success(request, 'Ваша почта успешно подтверждена!')
        except User.DoesNotExist:
            messages.error(request, 'Неверная или устаревшая ссылка подтверждения.')

        return redirect('users:login')


class BlockUserView(ManagerMixin, View):
    """
    Позволяет менеджерам блокировать или разблокировать пользователей.
    """
    template_name = 'users/block_user.html'

    def get(self, request):
        form = BlockUserForm()
        User = get_user_model()

        users = User.objects.exclude(is_superuser=True).exclude(groups__name='Managers')

        return render(request, self.template_name, {'form': form, 'users': users})

    def post(self, request):
        form = BlockUserForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['user_id']
            try:
                User = get_user_model()
                user_to_block = User.objects.get(pk=user_id)
                user_to_block.is_active = not user_to_block.is_active
                user_to_block.save()
                print("Пользователь успешно заблокирован")
                return redirect('users:block_user')
            except User.DoesNotExist:
                form.add_error('user_id', 'Пользователь не найден.')

users/templates/users/block_user.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-4">
    <h1>Список пользователей</h1>

    <table class="table table-bordered table-hover">
        <thead class="thead-dark">
        <tr>
            <th>Имя пользователя</th>
            <th>Email</th>
            <th>Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <td>
                {% if not user.first_name %}
                Не указано
                {% else %}
                {{ user.first_name }}
                {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <td>
                <form method="post" class="d-inline">
                    {% csrf_token %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                    {% if not user.is_superuser %}
                    {% if user.is_active %}
                    <button type="submit" class="btn btn-danger">Заблокировать</button>
                    {% else %}
                    <button type="submit" class="btn btn-success">Разблокировать</button>
                    {% endif %}
                    {% else %}
                    <p>Пользователь не доступен для блокировки</p>
                    {% endif %}
                </form>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12">
    {% if messages %}
    <div class="col-12 d-flex justify-content-center mt-3">
        <ul class="messages list-group w-50">
            {% for message in messages %}
            <li class="list-group-item text-center text-danger {% if message.tags %}list-group-item-{{ message.tags }}{% endif %}">{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <form class="row mt-3" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Вход
                    </h3>
                </div>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Войти</button>
                <a href="{% url 'users:update_password' %}" class="btn btn-danger">Забыли пароль?</a>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "mailing/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Ваш пароль был успешно изменен!</h2>
    <p><a href="{% url 'users:login' %}">Войти</a> с новым паролем.</p>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "mailing/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Введите новый пароль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.new_password1.label_tag }} {{ form.new_password1 }}
        {{ form.new_password2.label_tag }} {{ form.new_password2 }}
        <button type="submit" class="btn btn-primary">Изменить пароль</button>
    </form>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "mailing/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2>Инструкции по сбросу пароля были отправлены</h2>
    <p>Пожалуйста, проверьте свою электронную почту.</p>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
Здравствуйте!

Вы получили это письмо, потому что кто-то запросил сброс пароля для вашего аккаунта на {{ site_name }}.

Пожалуйста, перейдите по следующей ссылке, чтобы установить новый пароль:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

Если вы не запрашивали сброс пароля, просто проигнорируйте это письмо.

С уважением,
Команда {{ site_name }}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Сброс пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сбросить пароль</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="col-12 mt-5">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Регистрация
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                </div>
                <div class="card-footer">
                    <h5>Требования к паролю:</h5>
                    <ul>
                        <li>Минимум 8 символов.</li>
                        <li>Не похож на имя или почту.</li>
                        <li>Не состоит только из цифр.</li>
                    </ul>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}